### PR TITLE
Added myself to contributors

### PR DESCRIPTION
**Pull request by mohammadobaid1**
Issue #8

### CODE REVIEW

**Comment by arshadkazmi42** [comment]
@mohammadobaid1 looks good. can you tag the issue number in description.
Once that is done, i will merge it.

1 feedback, always work on a feature branch, its not good practice to work on master branch

**Comment by mohammadobaid1** [comment]
Just a noob question . By feature branch you mean creating new branch right ?

**Comment by arshadkazmi42** [comment]
yes. thats correct

**Comment by arshadkazmi42** [comment]
This Looks good. Merging it.

**Comment by mohammadobaid1** [comment]
Thanks . That was my first PR  :)

**Comment by arshadkazmi42** [comment]
Congrats on your first PR

**Pull request merged**
