### PR TITLE
Closes #44

### LINKED ISSUE #44: Fix broken link in Contributors.md
There is a Contributor added with wrong syntax in this file

https://github.com/arshadkazmi42/ak-json-to-joi/blob/master/Contributors.md

This needs to be fixed.

**Steps to work on the issue**

1. Comment here (eg: I am working on this or something like that)
2. Create PR.
3. Add this in your PR description `Closes #44` (Note: This should not go as a commit message.)
4. Do not work on forked master branch. Create a new branch when working on this.

**Note:** whoever comments here, gets the issue. Also if someone has taken the issue, do not create duplicate PRs

### PR DESCRIPTION
**Pull request by ShahSheel**
Closes #44

### CODE REVIEW

**Comment by arshadkazmi42** [comment]
You don't have to add it in your commit. Just add that `Closes #44` in the Comments here.

other than that it looks good. Code Quality Check was also failing for few users. We would love to fix it in this PR itself. let the checks complete. if anything fails we will fix it in this PR.

**Comment by arshadkazmi42** [comment]
@ShahSheel All checks passed. Can you update the PR description. i will merge it as soon as its done.

**Comment by ShahSheel** [comment]
@arshadkazmi42 Sorry this is my first, time. So i need to add a description to this pull request and not the commit file? I'm trying to update the pull request but not sure how.

**Comment by arshadkazmi42** [comment]
This looks good. Merging it. Congrats on your first PR.
Thank you for working on this.

**Pull request merged**
