### PR TITLE
Fixes: #8 : Added Me to Contributors

### PR DESCRIPTION
**Pull request by sk9331657**
Added Me to Contributors List.
Fixes: #8

### CODE REVIEW

**Comment by arshadkazmi42** [comment]
@sk9331657 Congrats on your first PR.

Small change needed here. Tag the issue number in PR description something like this `#8`

**Comment by sk9331657** [comment]
@arshadkazmi42  Why Codacy is failing ??

**Comment by arshadkazmi42** [comment]
@sk9331657 its indentation issue, I am ignoring it for now. I will be creating another issue to fix that.

**Comment by arshadkazmi42** [comment]
Congrats @sk9331657 on lading your first PR

**Comment by sk9331657** [comment]
@arshadkazmi42  Thanks.

**Pull request merged**
